audio:
  default_microphone: alsa_input.usb-Microsoft_Microsoft___LifeCam_HD-3000-02.pro-input-0
dictionary:
  a capo: r
  due punti: ':'
  punto: .
  punto e virgola: ;
  punto esclamativo: '!'
  punto interrogativo: '?'
  spazio: ' '
  virgola: ','
keywords:
  galileo cancella: cancella
  galileo chiudi: chiudi
  galileo correggi: correggi
  galileo manda: inserisci
  galileo pulisci: pulisci
  galileo scrivi: scrivi
llm:
  api_key: '' #in the env
  default_model: 1
  model1: anthropic/claude-3-haiku
  model2: meta-llama/llama-3.2-3b-instruct
settings:
  language: it
  multi_model_mode: "best_confidence"
  confidence_threshold: 0.7
  primary_secondary_confidence_threshold_level: 0.15
  popup_position: top-right
  timeout_seconds: 6000
  vosk_model_path: /home/marco/voice_text_insert/model/vosk-model-small-it-0.22
vosk_models:
  it:
    path: /home/marco/voice_text_insert/model/vosk-model-small-it-0.22
    enabled: true
    primary: true
  en:
    path: /home/marco/voice_text_insert/model/vosk-model-small-en-us-0.15
    enabled: true
    primary: false
